# Generated by Django 5.1.15 on 2026-08-06 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storage", "0014_file_description_file_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trashed_root",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tables",
                        to="storage.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tables_table",
            },
        ),
        migrations.CreateModel(
            name="Row",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("position", models.FloatField(default=0)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "db_table": "tables_row",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("long_text", "Long text"),
                            ("number", "Number"),
                            ("checkbox", "Checkbox"),
                            ("single_select", "Single select"),
                            ("date", "Date"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict)),
                ("position", models.FloatField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "db_table": "tables_field",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="View",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Grid", max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("grid", "Grid")], default="grid", max_length=12
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("position", models.FloatField(default=0)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "db_table": "tables_view",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["owner", "folder", "deleted_at"],
                name="tables_tabl_owner_i_abe16a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="row",
            index=models.Index(
                fields=["table", "position"], name="tables_row_table_i_8f85bc_idx"
            ),
        ),
    ]
