# Generated by Django 5.1.15 on 2026-08-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("long_text", "Long text"),
                    ("number", "Number"),
                    ("checkbox", "Checkbox"),
                    ("single_select", "Single select"),
                    ("multi_select", "Multi select"),
                    ("date", "Date"),
                    ("url", "URL"),
                    ("email", "Email"),
                    ("rating", "Rating"),
                    ("currency", "Currency"),
                    ("percent", "Percent"),
                ],
                default="text",
                max_length=16,
            ),
        ),
    ]
