# Generated by Django 5.1.15 on 2026-08-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0005_alter_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="view",
            name="kind",
            field=models.CharField(
                choices=[("grid", "Grid"), ("kanban", "Kanban")],
                default="grid",
                max_length=12,
            ),
        ),
    ]
