# Generated by Django 5.1.15 on 2026-07-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Grievance",
        ),
    ]
