# Generated by Django 5.1.15 on 2026-07-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("quota", "Quota"),
                    ("security", "Security"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
