import React from 'react';
import { hov } from '../lib/ui';

// Extracted from AppShell.
export default function TopBarDesktop(V) {
  return (
    (V.isDesktop) ? (<React.Fragment>{' '}<div style={{"flex":"1","display":"flex","alignItems":"center","gap":"9px","background":"#F1F2F5","border":"1px solid #E5E7EC","borderRadius":"10px","padding":"9px 13px","maxWidth":"380px"}}>{' '}<svg width="16" height="16" viewBox="0 0 24 24" fill="none"><circle cx="11" cy="11" r="7" stroke="#8A909B" strokeWidth="1.8" /><path d="M20 20l-4.3-4.3" stroke="#8A909B" strokeWidth="1.8" strokeLinecap="round" /></svg>{' '}<input value={V.searchQuery} onInput={V.setSearch} placeholder="Search files, folders, channels" style={{"background":"none","border":"none","outline":"none","color":"#15171C","fontSize":"13.5px","fontFamily":"'IBM Plex Sans',sans-serif","width":"100%"}} />{' '}{(V.searchActive) ? (<React.Fragment><button onClick={V.clearSearch} style={{"background":"none","border":"none","cursor":"pointer","color":"#9AA1AC","display":"flex","padding":"0"}}><svg width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="M5 5l14 14M19 5L5 19" stroke="currentColor" strokeWidth="2" strokeLinecap="round" /></svg></button></React.Fragment>) : null}{' '}</div>{' '}<div style={{"flex":"1"}} />{' '}<button onClick={V.openNewFolder} style={{"display":"flex","alignItems":"center","gap":"7px","background":"#FFFFFF","color":"#15171C","border":"1px solid #E5E7EC","borderRadius":"10px","padding":"10px 14px","fontSize":"13.5px","fontWeight":"600","cursor":"pointer","fontFamily":"'IBM Plex Sans',sans-serif"}} {...hov({"background":"#F1F2F5"})}><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z" stroke="#656B76" strokeWidth="1.7" /><path d="M12 11v4M10 13h4" stroke="#656B76" strokeWidth="1.7" strokeLinecap="round" /></svg>New folder</button>{' '}<button onClick={V.openUpload} style={{"display":"flex","alignItems":"center","gap":"7px","background":"#5145E5","color":"#fff","border":"none","borderRadius":"10px","padding":"10px 16px","fontSize":"13.5px","fontWeight":"600","cursor":"pointer","fontFamily":"'IBM Plex Sans',sans-serif"}} {...hov({"background":"#4238CC"})}><svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M12 16V4M7 9l5-5 5 5M4 20h16" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /></svg>Upload</button>{' '}<button onClick={V.openSettings} style={{"width":"34px","height":"34px","borderRadius":"50%","background":"#5145E5","border":"none","display":"flex","alignItems":"center","justifyContent":"center","fontSize":"13px","fontWeight":"600","color":"#fff","fontFamily":"'Space Grotesk',sans-serif","cursor":"pointer"}}>A</button>{' '}</React.Fragment>) : null
  );
}
