# Generated by Django 5.1.15 on 2026-07-23 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralBonus",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bytes", models.BigIntegerField(default=53687091200)),
                ("expires_at", models.DateTimeField()),
                (
                    "referee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_by_bonus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_bonuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_referral_bonus",
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gateway", models.CharField(default="razorpay", max_length=20)),
                ("event_id", models.CharField(max_length=128)),
                ("event_type", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "db_table": "billing_webhook_event",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gateway", "event_id"), name="uniq_gateway_event"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_code", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("past_due", "Past due"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "gateway_subscription_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscription",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="billing_sub_user_id_fe5b98_idx"
                    )
                ],
            },
        ),
    ]
