# Generated by Django 5.1.15 on 2026-07-29 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storage", "0009_remove_file_is_quarantined_alter_file_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphBuild",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                ("node_count", models.PositiveIntegerField(default=0)),
                ("edge_count", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_build",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "graph_build",
            },
        ),
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("file", "File"), ("folder", "Folder")], max_length=8
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("node_type", models.CharField(default="file", max_length=16)),
                (
                    "scope_folder_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_nodes",
                        to="storage.file",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_nodes",
                        to="storage.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "graph_node",
            },
        ),
        migrations.CreateModel(
            name="GraphEdge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rel",
                    models.CharField(
                        choices=[
                            ("contains", "Contains"),
                            ("references", "References"),
                            ("shared_token", "Shared token"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("extracted", "Extracted"),
                            ("inferred", "Inferred"),
                            ("ambiguous", "Ambiguous"),
                        ],
                        default="extracted",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_edges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_edges",
                        to="graph.graphnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_edges",
                        to="graph.graphnode",
                    ),
                ),
            ],
            options={
                "db_table": "graph_edge",
            },
        ),
        migrations.AddIndex(
            model_name="graphnode",
            index=models.Index(
                fields=["owner", "kind"], name="graph_node_owner_i_e895ae_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="graphnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("file__isnull", False)),
                fields=("owner", "file"),
                name="uniq_node_per_file",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("folder__isnull", False)),
                fields=("owner", "folder"),
                name="uniq_node_per_folder",
            ),
        ),
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(
                fields=["owner", "rel"], name="graph_edge_owner_i_3a0bcc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="graphedge",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "rel"), name="uniq_edge"
            ),
        ),
    ]
