# Generated by Django 5.1.15 on 2026-08-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0002_alter_graphedge_rel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphnode",
            name="kind",
            field=models.CharField(
                choices=[
                    ("file", "File"),
                    ("folder", "Folder"),
                    ("table", "Table"),
                    ("row", "Row"),
                ],
                max_length=8,
            ),
        ),
    ]
