# Generated by Django 5.1.15 on 2026-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0003_alter_graphnode_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphedge",
            name="rel",
            field=models.CharField(
                choices=[
                    ("contains", "Contains"),
                    ("references", "References"),
                    ("shared_token", "Shared token"),
                    ("shared_tag", "Shared tag"),
                    ("attaches", "Attaches"),
                ],
                max_length=20,
            ),
        ),
    ]
