# Generated by Django 5.1.15 on 2026-07-23 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("flag", "Flag"), ("report", "Report")], max_length=8
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("channel", "Channel"),
                            ("post", "Channel post"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target_id", models.UUIDField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("copyright", "Copyright / IP"),
                            ("inappropriate", "Inappropriate content"),
                            ("csam", "CSAM"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("confirmed", "Confirmed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "moderation_content_report",
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "status"],
                        name="moderation__target__c779ba_idx",
                    )
                ],
            },
        ),
    ]
