# Generated by Django 5.1.15 on 2026-07-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentreport",
            name="target_type",
            field=models.CharField(choices=[("file", "File")], max_length=10),
        ),
    ]
