# Generated by Django 5.1.15 on 2026-07-23 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="storage.folder",
                    ),
                ),
            ],
            options={
                "db_table": "storage_folder",
            },
        ),
        migrations.CreateModel(
            name="StorageObject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("region", models.CharField(max_length=16)),
                ("size_bytes", models.BigIntegerField()),
                ("ref_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scanning", "Scanning"),
                            ("ready", "Ready"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="scanning",
                        max_length=12,
                    ),
                ),
                (
                    "object_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
            ],
            options={
                "db_table": "storage_object",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_hash", "region"), name="uniq_hash_per_region"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("doc", "Document"),
                        ],
                        default="file",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending upload"),
                            ("scanning", "Scanning"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="storage.folder",
                    ),
                ),
                (
                    "storage_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="storage.storageobject",
                    ),
                ),
            ],
            options={
                "db_table": "storage_file",
            },
        ),
        migrations.CreateModel(
            name="StorageReservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bytes", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("committed", "Committed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="storage.file",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "storage_reservation",
            },
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["owner", "parent", "deleted_at"],
                name="storage_fol_owner_i_67abdb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["owner", "folder", "deleted_at"],
                name="storage_fil_owner_i_2f8348_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storagereservation",
            index=models.Index(
                fields=["owner", "status", "expires_at"],
                name="storage_res_owner_i_8a20a9_idx",
            ),
        ),
    ]
