# Generated by Django 5.1.15 on 2026-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="is_quarantined",
            field=models.BooleanField(default=False),
        ),
    ]
