# Generated by Django 5.1.15 on 2026-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_file_is_quarantined"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="stream_uid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
