# Generated by Django 5.1.15 on 2026-07-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_file_stream_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="is_frozen",
            field=models.BooleanField(default=False),
        ),
    ]
