# Generated by Django 5.1.15 on 2026-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_file_is_frozen"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="is_discoverable",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="file",
            name="is_mature_content",
            field=models.BooleanField(default=False),
        ),
    ]
