# Generated by Django 5.1.15 on 2026-07-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_file_is_discoverable_file_is_mature_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="stream_uid",
        ),
        migrations.AddField(
            model_name="file",
            name="duration_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="playable_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playable_for",
                to="storage.storageobject",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="poster_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="poster_for",
                to="storage.storageobject",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending upload"),
                    ("scanning", "Scanning"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
