# Generated by Django 5.1.15 on 2026-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_remove_file_stream_uid_file_duration_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="trashed_root",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="folder",
            name="trashed_root",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
