# Generated by Django 5.1.15 on 2026-07-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0007_file_trashed_root_folder_trashed_root"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="is_frozen",
        ),
    ]
