# Generated by Django 5.1.15 on 2026-07-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0008_remove_file_is_frozen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="is_quarantined",
        ),
        migrations.AlterField(
            model_name="file",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending upload"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="storageobject",
            name="status",
            field=models.CharField(
                choices=[("ready", "Ready")], default="ready", max_length=12
            ),
        ),
    ]
