# Generated by Django 5.1.15 on 2026-07-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0009_remove_file_is_quarantined_alter_file_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="content_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
