# Generated by Django 5.1.15 on 2026-07-31 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_file_content_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[("local", "Local disk"), ("r2", "Cloudflare R2")],
                        default="local",
                        max_length=8,
                    ),
                ),
                (
                    "r2_endpoint_url",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "r2_access_key_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("r2_secret_ciphertext", models.TextField(blank=True, default="")),
                ("r2_bucket", models.CharField(blank=True, default="", max_length=200)),
                ("setup_completed", models.BooleanField(default=False)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "storage_config",
            },
        ),
        migrations.CreateModel(
            name="StorageMigration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                ("done", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
                ("failed", models.IntegerField(default=0)),
                ("bytes_moved", models.BigIntegerField(default=0)),
                ("delete_local", models.BooleanField(default=False)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "storage_migration",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="storage_mig_status_66b99e_idx",
                    )
                ],
            },
        ),
    ]
