# Generated by Django 5.1.15 on 2026-08-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0011_storageconfig_storagemigration"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageconfig",
            name="allow_overflow",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storageconfig",
            name="r2_quota_bytes",
            field=models.BigIntegerField(default=10995116277760),
        ),
    ]
