# Generated by Django 5.1.15 on 2026-08-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0012_storageconfig_allow_overflow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="starred",
            field=models.BooleanField(default=False),
        ),
    ]
