# Generated by Django 5.1.15 on 2026-08-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0013_file_starred"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="file",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
