# Generated by Django 5.1.15 on 2026-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="quota_bytes",
            field=models.BigIntegerField(default=536870912000),
        ),
        migrations.AddField(
            model_name="user",
            name="storage_used_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("paid_2tb", "Paid 2TB"),
                    ("paid_5tb", "Paid 5TB"),
                ],
                default="free",
                max_length=10,
            ),
        ),
    ]
