# Generated by Django 5.1.15 on 2026-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_dataexport_consentlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_backup_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="backup_wifi_only",
            field=models.BooleanField(default=True),
        ),
    ]
