# Generated by Django 5.1.15 on 2026-07-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="scopes",
            field=models.CharField(default="read,write", max_length=64),
        ),
    ]
