# Generated by Django 5.1.15 on 2026-07-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_two_factor_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="referral_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="referred_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tier",
        ),
        migrations.AlterField(
            model_name="user",
            name="quota_bytes",
            field=models.BigIntegerField(default=2199023255552),
        ),
    ]
