# Generated by Django 5.1.15 on 2026-07-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_user_referral_code_remove_user_referred_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_verified_at",
        ),
    ]
