# Generated by Django 5.1.15 on 2026-07-29 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_user_phone_remove_user_phone_verified_and_more"),
        ("storage", "0009_remove_file_is_quarantined_alter_file_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="root_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scoped_api_keys",
                to="storage.folder",
            ),
        ),
    ]
