# Generated by Django 5.1.15 on 2026-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_apikey_root_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
    ]
