# Generated by Django 5.1.15 on 2026-08-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_is_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
