# Generated by Django 5.1.15 on 2026-08-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_user_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(blank=True, default="en", max_length=8),
        ),
    ]
